import './globals.css';
import Footer from './components/Footer/Footer';
import ContactButtons from './components/ContactButtons';


export const metadata = {
  title: 'dSign',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        
        <Footer />
        <ContactButtons />
      </body>
    </html>
  )
}
